# === CONFIGURACION SonarCLoud ===
sonar.projectKey=Paulo_Miranda_t1
sonar.sources=src
sonar.exclusions=.venv/**, **/__pycache__/**, **/__init__.py
sonar.host.url=http://localhost:9000
sonar.token=squ_0c3b1ceea8ab38fbfea160535bf7f1bb27e5e385

# CONFIGURACION DE PRUEBAS Y COBERTURA 
sonar.tests=test
sonar.test.inclusions=**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/__init__.py, dont-touch/**

